# -*- coding: utf-8 -*-
"""NutriClass-LogisticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9NwOS7WAAH7E2bjcgkHT-_7oLtbxfhI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from sklearn.linear_model import  LogisticRegression

pre_processed_food_data_df = pd.read_csv('/content/preprocessed_food_data.csv')
pre_processed_food_data_df.head()

X = pre_processed_food_data_df.drop("Food_Name", axis=1)
y = pre_processed_food_data_df["Food_Name"]

num_cols = X.select_dtypes(include=["int64", "float64"]).columns
cat_cols = X.select_dtypes(include=["object", "bool"]).columns

numeric_pipeline = Pipeline([
    ("scaler", StandardScaler())
])
numeric_pipeline

categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, num_cols),
    ("cat", categorical_pipeline, cat_cols)
])
preprocessor

# train Test Split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

Model=Pipeline(steps=[
    ('Preprocess_Step',preprocessor),
    ('Classifier',LogisticRegression())
])
Model

Model.fit(X_train,y_train)

# Predict For X_Train and X_Test

y_pred_train=Model.predict(X_train)
y_pred_test=Model.predict(X_test)

# Evaluate the Model For Both Train And Test
print('Logistic Regression - Classification Report For Train')
print(classification_report(y_train,y_pred_train))
print('Logistic Regression - Classification Report For Test')
print(classification_report(y_test,y_pred_test))