# -*- coding: utf-8 -*-
"""NutriClass-GradientBoostingClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9RJn8R1AFCxWzQ9aMJ6xCoebE_7iS96
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from sklearn.ensemble import GradientBoostingClassifier

processed_food_df = pd.read_csv('/content/preprocessed_food_data.csv')
processed_food_df.head()

## Identify Features & Target

X = processed_food_df.drop("Food_Name", axis=1)
y = processed_food_df["Food_Name"]

## Separate Numerical & Categorical Columns

num_cols = X.select_dtypes(include=["int64", "float64"]).columns
cat_cols = X.select_dtypes(include=["object", "bool"]).columns

## Preprocessing Pipeline

numeric_pipeline = Pipeline([
    ("scaler", StandardScaler())
])
numeric_pipeline

categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])
categorical_pipeline

## Combine Using ColumnTransformer ##

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, num_cols),
    ("cat", categorical_pipeline, cat_cols)
])
preprocessor

## Train-Test Split ##

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

Model=Pipeline(steps=[
    ('Preprocess_Step',preprocessor),
     ('GradientBoost_classifier',GradientBoostingClassifier())
])

Model.fit(X_train, y_train)

## Model Predict Evaluation ##

y_pred_train=Model.predict(X_train)
y_pred_test=Model.predict(X_test)

## accuracy check process ##

accuracy = accuracy_score(y_test, y_pred_test)
accuracy

# Evaluate the Model For Both Train And Test
print('Gradient Boosting - Classification Report For Train')
print(classification_report(y_train,y_pred_train))
print('Gradient Boosting - Classification Report For Test')
print(classification_report(y_test,y_pred_test))